[package]
name = "cmdshelf"
version = "1.1.0"
authors = ["toshi0383 <t.suzuki326@gmail.com>"]

[dependencies]
is_executable = "0.1.0"
walkdir = "2"
toml = "0.4"
serde = "1"
serde_derive = "1"

[profile.release]
opt-level = 3
